target 'PerfAnalysis' do
  pod 'FirebaseCrashlytics', :path => '../Unwinding'
end

# Crashlytics fails to build for the x86_64 simulator, so force this to be only the active arch
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = 'arm64'
        end
    end
end
