use_frameworks! :linkage => :static

target 'PerfAnalysis' do
  pod 'FirebaseCrashlytics', :path => '../Unwinding'
  pod 'PeerTalk', '0.1.0'
end

target 'PerfAnalysisRunner' do
  pod 'PeerTalk', '0.1.0'
end
